const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const SERVER_ERROR_STATUS_CODE = 500;
const CONFLICT_ERROR_STATUS_CODE = 409;
const NOT_AUTHORIZED_STATUS_CODE = 401;
const FORBIDDEN_STATUS_CODE = 403;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  NOT_FOUND_STATUS_CODE,
  SERVER_ERROR_STATUS_CODE,
  CONFLICT_ERROR_STATUS_CODE,
  NOT_AUTHORIZED_STATUS_CODE,
  FORBIDDEN_STATUS_CODE,
};
